# base configurations
dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements-ci.txt

# command to run tests
script:
  - coverage run tests/test.py

# coverage
after_success:
  - codecov
